### ISSUE TITLE
Hi, I use this package but I had a problem with the flutter_map package

### ISSUE THREAD

**Issue by xusanFlutter** [OPENER-next/animated_location_indicator#2]
https://github.com/OPENER-next/animated_location_indicator/assets/102403635/227587cc-d363-4c60-a037-7272105e2cb6

**Comment by Robbendebiene** [comment]
Without further information like the flutter_map version as well as a more detailed description of the problem I cannot help you.

**Comment by Robbendebiene** [comment]
Without further information like the flutter_map version as well as a more detailed description of the problem I cannot help you.
